name: lumora
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.0
  cupertino_icons: ^1.0.8
  lottie: ^3.0.0
  http: ^1.1.0
  file_picker: ^6.1.0
  universal_platform: ^1.0.0
  video_player: ^2.10.0
  url_launcher: ^6.3.2
  dio: ^5.9.0
  syncfusion_flutter_maps: ^31.1.19
  syncfusion_flutter_charts: ^31.1.19



  
dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

